#!/usr/bin/env python3
"""Verify the Workspace Agents operator action queue UI contract."""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
AI_EMPLOYEES = ROOT / "ui" / "start-building-app" / "src" / "app" / "components" / "pages" / "AIEmployees.tsx"
LIVE_API = ROOT / "ui" / "start-building-app" / "src" / "app" / "data" / "liveApi.ts"


SECRET_PATTERNS = [
    re.compile(r"Authorization:", re.IGNORECASE),
    re.compile(r"Bearer\s+[A-Za-z0-9._~+/=-]+"),
    re.compile(r"agtok_[A-Za-z0-9_]+"),
    re.compile(r"agtsess_[A-Za-z0-9_]+"),
    re.compile(r"sk-[A-Za-z0-9]{8,}"),
    re.compile(r"ntn_[A-Za-z0-9]{8,}"),
    re.compile(r"AGENTOPS_API_KEY=", re.IGNORECASE),
]


EXPECTED_MARKERS = {
    "loop_first_issue_recovery": "loop-first-issue:",
    "loop_first_issue_verify": "verifyAction: loopAuditNextAction",
    "loop_action_package_source": "operatorLoopAudit?.action_package",
    "loop_action_package_items": "loopActionPackageItems",
    "loop_work_order_label_en": 'loopWorkOrderTitle: "Loop work order"',
    "loop_work_order_label_zh": 'loopWorkOrderTitle: "Loop 执行包"',
    "loop_work_order_summary_en": 'loopWorkOrderSummary: "Copy the next gate action',
    "loop_work_order_summary_zh": 'loopWorkOrderSummary: "从 loop action package',
    "loop_launch_packet_import": "loadOperatorLoopLaunchPacket",
    "loop_launch_packet_loader": 'id: "operator_loop_launch_packet", load: async () => ({ operatorLoopLaunchPacket: await loadOperatorLoopLaunchPacket(8) })',
    "loop_launch_packet_data": "operatorLoopLaunchPacket",
    "loop_launch_packet_type": "OperatorLoopLaunchPacketPayload",
    "loop_launch_contract_title_en": 'loopLaunchContractTitle: "Loop launch contract"',
    "loop_launch_contract_title_zh": 'loopLaunchContractTitle: "Loop 启动契约"',
    "loop_launch_eval_contract": "loopLaunchEvaluationContract",
    "loop_launch_audit_contract": "loopLaunchAuditContract",
    "loop_launch_required_ledgers": "loopLaunchRequiredLedgers",
    "loop_launch_exit_criteria": "loopLaunchExitCriteria",
    "loop_launch_execution_chain": "loopLaunchExecutionChain",
    "loop_launch_mutating_steps": "loopLaunchMutatingSteps",
    "loop_launch_receipt_steps": "loopLaunchReceiptSteps",
    "loop_launch_execution_chain_json": "execution_chain: operatorLoopLaunchPacket.execution_chain",
    "loop_launch_control_summary_json": "control_summary: operatorLoopLaunchPacket.control_summary",
    "loop_launch_control_summary": "loopLaunchControlSummary",
    "loop_launch_control_title_en": 'loopControlTitle: "Loop control"',
    "loop_launch_control_title_zh": 'loopControlTitle: "Loop 控制"',
    "loop_launch_recommended_step": "loopLaunchRecommendedStep",
    "loop_launch_recommended_command": "loopLaunchRecommendedCommand",
    "loop_launch_control_copy_only": "loopLaunchControlSummary.server_executes_shell",
    "loop_launch_execution_chain_label_en": 'executionChain: "Execution chain"',
    "loop_launch_execution_chain_label_zh": 'executionChain: "执行链"',
    "loop_launch_execution_chain_copy_action": "copyIntakeCommand(step.command)",
    "loop_launch_execution_chain_copy_verify": "copyIntakeCommand(String(step.verify_command))",
    "loop_launch_execution_chain_confirm_label": "step.confirm_required ? copy.confirmRequired",
    "loop_launch_execution_chain_receipt_label": "step.receipt_required",
    "loop_launch_execution_chain_status": "step.step_status",
    "loop_launch_execution_chain_reason": "step.blocked_reason || step.ready_reason",
    "loop_launch_execution_chain_receipt_state": "step.receipt_state",
    "loop_launch_tamper_chain": "loopLaunchAuditContract?.tamper_chain_required",
    "loop_launch_copy_json": "copyIntakeCommand(loopLaunchPacketJson)",
    "panel_badge_loop_launch": 'panelStatusBadge("operator_loop_launch_packet")',
    "panel_refresh_loop_launch": 'panelRefreshButton("operator_loop_launch_packet")',
    "panel_diagnostics_loop_launch": 'panelDiagnosticsButton("operator_loop_launch_packet")',
    "panel_receipt_loop_launch": 'panelReceiptButton("operator_loop_launch_packet")',
    "loop_action_package_action_copy": "copyIntakeCommand(item.action_command)",
    "loop_action_package_verify_copy": "copyIntakeCommand(item.verify_command)",
    "loop_action_package_receipt_copy": "copyIntakeCommand(item.receipt_record_command)",
    "loop_action_package_verify_receipt_copy": "copyIntakeCommand(item.receipt_verify_record_command)",
    "panel_loader_manifest": "AI_EMPLOYEES_PANEL_LOADERS",
    "panel_loader_core_manifest": "AI_EMPLOYEES_CORE_PANEL_LOADERS",
    "panel_loader_deferred_manifest": "AI_EMPLOYEES_DEFERRED_PANEL_LOADERS",
    "panel_loader_scoped_manifest": "AI_EMPLOYEES_SCOPED_PANEL_LOADERS",
    "panel_loader_all_settled": "Promise.allSettled(loaders.map",
    "panel_loader_state": "panelLoadState",
    "panel_loader_deferred_state": "deferredLoading",
    "panel_loader_deferred_error": "deferredError",
    "panel_loader_visible_badge": "panelStatusBadge",
    "panel_loader_ready_label": "panelLoadReady",
    "panel_loader_unavailable_label": "panelLoadUnavailable",
    "panel_loader_loading_label": "panelLoadLoading",
    "panel_local_refresh_function": "const refreshPanel = useCallback",
    "panel_local_refresh_button": "panelRefreshButton",
    "panel_local_refresh_label": "refreshPanel:",
    "panel_local_refresh_running_label": "panelRefreshRunning",
    "panel_attempts": "panel_attempts",
    "panel_updated_at": "panel_updated_at",
    "panel_last_error": "panel_last_error",
    "panel_diagnostics_json": "panel_diagnostics_json",
    "panel_copy_diagnostics_label": "copyPanelDiagnostics",
    "panel_copy_diagnostics_token_omitted": "token_omitted",
    "panel_record_diagnostics_label": "recordPanelDiagnostics",
    "panel_record_receipt_result": "panelReceiptRecorded",
    "panel_record_receipt_function": "recordPanelDiagnosticReceipt",
    "panel_record_receipt_source": 'source: "ui.panel_diagnostics"',
    "panel_record_receipt_action_id": "ui_panel_diagnostics:${panelId}",
    "panel_record_receipt_verify": 'verify_command: "agentops operator action-receipts --limit 20"',
    "panel_record_receipt_refresh": 'refreshPanel("operator_action_receipts")',
    "panel_badge_header": 'panelStatusBadge("worker_status")',
    "panel_refresh_header": 'panelRefreshButton("worker_status")',
    "panel_diagnostics_header": 'panelDiagnosticsButton("worker_status")',
    "panel_receipt_header": 'panelReceiptButton("worker_status")',
    "panel_badge_action_plan": 'panelStatusBadge("operator_action_plan")',
    "panel_refresh_action_plan": 'panelRefreshButton("operator_action_plan")',
    "panel_diagnostics_action_plan": 'panelDiagnosticsButton("operator_action_plan")',
    "panel_receipt_action_plan": 'panelReceiptButton("operator_action_plan")',
    "panel_badge_evidence_report": 'panelStatusBadge("operator_evidence_report")',
    "panel_refresh_evidence_report": 'panelRefreshButton("operator_evidence_report")',
    "panel_diagnostics_evidence_report": 'panelDiagnosticsButton("operator_evidence_report")',
    "panel_receipt_evidence_report": 'panelReceiptButton("operator_evidence_report")',
    "panel_badge_loop_audit": 'panelStatusBadge("operator_loop_audit")',
    "panel_refresh_loop_audit": 'panelRefreshButton("operator_loop_audit")',
    "panel_diagnostics_loop_audit": 'panelDiagnosticsButton("operator_loop_audit")',
    "panel_receipt_loop_audit": 'panelReceiptButton("operator_loop_audit")',
    "panel_badge_handoff": 'panelStatusBadge("operator_handoff")',
    "panel_refresh_handoff": 'panelRefreshButton("operator_handoff")',
    "panel_diagnostics_handoff": 'panelDiagnosticsButton("operator_handoff")',
    "panel_receipt_handoff": 'panelReceiptButton("operator_handoff")',
    "operator_handoff_loader": 'id: "operator_handoff", load: async (context) => ({ operatorHandoff: await loadOperatorHandoff(12, String(context.scopedLoopId || "")) })',
    "operator_health_loader": 'id: "operator_health", load: async (context) => ({ operatorHealth: await loadOperatorHealth(12, String(context.scopedLoopId || "")) })',
    "operator_health_data": "operatorHealth",
    "operator_health_label_en": 'operatorHealthTitle: "Operator health"',
    "operator_health_label_zh": 'operatorHealthTitle: "Operator 健康"',
    "operator_health_summary_en": 'operatorHealthSummary: "Aggregate read-only health',
    "operator_health_summary_zh": 'operatorHealthSummary: "聚合 Loop 交接',
    "operator_health_score_label_en": 'healthScore: "Health score"',
    "operator_health_score_label_zh": 'healthScore: "健康分"',
    "operator_health_risks_label_en": 'healthRisks: "Health risks"',
    "operator_health_risks_label_zh": 'healthRisks: "健康风险"',
    "operator_health_score_render": "operatorHealth?.score ?? 0",
    "operator_health_risk_queue_source": 'item.lane === "operator_health"',
    "operator_health_risk_source_label": "copy.operatorHealthTitle : copy.operatorTitle",
    "operator_health_risk_backend_receipt": "receiptRecordCommand: item.receipt_record_command",
    "operator_health_risk_backend_verify_receipt": "receiptVerifyRecordCommand: item.receipt_verify_record_command",
    "operator_health_risk_sort": "candidate.isOperatorHealthRisk ? 118",
    "operator_health_control_summary": "operatorHealthControlSummary = operatorHealth?.control_summary || handoffControlSummary",
    "operator_health_loop_control": "operatorHealth?.loop_control ||",
    "operator_health_loop_control_badge": 'label={`${copy.loopControlTitle}: ${loopControlGateStatus}`}',
    "operator_health_loop_control_grid": "{ label: copy.loopControlTitle, value: loopControlSelectedGate, status: loopControlGateStatus }",
    "operator_health_loop_control_readback": "{ label: copy.controlReadbackSource, value: loopControlReadbackSource",
    "operator_health_loop_control_refresh": "{ label: copy.cacheRefresh, value: loopControlRefreshRequired",
    "operator_health_loop_control_command_source": "{ label: copy.commandSource, value: String(operatorHealthLoopControl.source",
    "operator_evidence_report_import": "loadOperatorEvidenceReport",
    "operator_evidence_report_loader": "loadOperatorEvidenceReport(8)",
    "operator_evidence_report_data": "operatorEvidenceReport",
    "operator_evidence_report_type": "OperatorEvidenceReportPayload",
    "operator_evidence_report_label_en": 'evidenceReportTitle: "Evidence report"',
    "operator_evidence_report_label_zh": 'evidenceReportTitle: "证据报告"',
    "operator_evidence_report_summary_en": 'evidenceReportSummary: "Run-level delivery evidence matrix',
    "operator_evidence_report_summary_zh": 'evidenceReportSummary: "按 run 聚合',
    "operator_evidence_report_commands": "operatorEvidenceCommands",
    "operator_evidence_report_top_runs": "operatorEvidenceTopRuns",
    "operator_evidence_report_copy": "copyIntakeCommand(firstCommand)",
    "operator_evidence_report_route": 'to={`/admin/runs/${run.run_id}`}',
    "operator_evidence_report_ready_label_en": 'evidenceReportReady: "Ready runs"',
    "operator_evidence_report_ready_label_zh": 'evidenceReportReady: "就绪 Run"',
    "operator_evidence_report_missing_label_en": 'missingManifests: "Missing manifests"',
    "operator_evidence_report_missing_label_zh": 'missingManifests: "缺失清单"',
    "operator_evidence_report_receipt_label_en": 'verifiedReceipts: "Verified receipts"',
    "operator_evidence_report_receipt_label_zh": 'verifiedReceipts: "已验收收据"',
    "daemon_logs_lazy_state": "daemonLogsOpen",
    "daemon_logs_lazy_loader": "loadSelectedDaemonLog",
    "daemon_logs_lazy_effect_guard": "if (!daemonLogsOpen) return;",
    "daemon_logs_lazy_open_label_en": 'openDaemonLogs: "Open logs"',
    "daemon_logs_lazy_open_label_zh": 'openDaemonLogs: "打开日志"',
    "daemon_logs_lazy_hint_en": 'daemonLogsLazyHint: "Logs are loaded only when opened',
    "daemon_logs_lazy_hint_zh": 'daemonLogsLazyHint: "日志只在打开时加载',
    "daemon_logs_lazy_selected_adapter": "setDaemonLogsOpen(true);",
    "daemon_logs_lazy_refresh": "void loadSelectedDaemonLog(selectedLogAdapter)",
    "security_readiness_local_write_guard_gate": "localWriteGuardGate",
    "security_readiness_visible_gates": "visibleSecurityGates",
    "security_readiness_local_write_guard_id": "local_ui_write_guard",
    "security_readiness_local_write_guard_label_en": 'localWriteGuard: "Local write guard"',
    "security_readiness_local_write_guard_label_zh": 'localWriteGuard: "本地写保护"',
    "security_readiness_local_write_guard_summary_en": 'localWriteGuardSummary: "Browser/local POST and PATCH',
    "security_readiness_local_write_guard_summary_zh": 'localWriteGuardSummary: "共享部署前',
    "security_readiness_local_write_guard_detail": "localWriteGuardGate?.detail",
    "security_readiness_local_write_guard_next_action": "localWriteGuardGate?.next_action",
    "production_security_prominent_strip": 'data-testid="production-security-warning-strip"',
    "production_security_prominent_status": "productionSecurityStatus",
    "production_security_prominent_attention": "productionSecurityNeedsAttention",
    "production_security_prominent_next_action": "productionSecurityNextAction",
    "production_security_prominent_copy": "copyIntakeCommand(productionSecurityNextAction)",
    "production_security_prominent_label_en": 'productionSecurityWarning: "Production security boundary"',
    "production_security_prominent_label_zh": 'productionSecurityWarning: "生产安全边界"',
    "production_security_prominent_summary_en": 'productionSecurityWarningSummary: "Shared/production use',
    "production_security_prominent_summary_zh": 'productionSecurityWarningSummary: "共享/生产使用前',
    "production_security_prominent_startup": "securityReadiness?.startup_security?.status",
    "receipt_evaluation_label_en": 'receiptEvaluation: "Receipt eval"',
    "receipt_evaluation_label_zh": 'receiptEvaluation: "收据评估"',
    "receipt_evaluation_queue_field": "receiptEvaluation: item.receipt_evaluation",
    "receipt_evaluation_queue_status": "queueReceiptEvaluationStatus",
    "receipt_evaluation_recovery_sort": "candidate.isReceiptEvaluationRecovery ? 116",
    "receipt_evaluation_coverage_render": "operatorReceiptCoverage.evaluation_coverage_percent",
    "receipt_failure_memory_label_en": 'receiptFailureMemoryTitle: "Receipt failure memory"',
    "receipt_failure_memory_label_zh": 'receiptFailureMemoryTitle: "失败收据记忆"',
    "receipt_failure_memory_source": "receiptFailureMemoryRaw",
    "receipt_failure_memory_handoff": "operatorHandoff?.receipt_state.failure_memory",
    "receipt_failure_memory_plan": "operatorActionPlan?.receipt_failure_memory",
    "receipt_failure_memory_candidate_count": "receiptFailureMemoryCandidateCount",
    "receipt_failure_memory_next_action": "receiptFailureMemoryNextAction",
    "receipt_failure_memory_copy": "copyIntakeCommand(receiptFailureMemoryNextAction)",
    "receipt_failure_memory_api_import": "proposeReceiptFailureMemory",
    "receipt_failure_memory_handler": "handleReceiptFailureMemory",
    "receipt_failure_memory_preview_call": "handleReceiptFailureMemory(false)",
    "receipt_failure_memory_confirm_call": "handleReceiptFailureMemory(true)",
    "receipt_failure_memory_confirm_label_en": 'createFailureMemory: "Create candidate"',
    "receipt_failure_memory_confirm_label_zh": 'createFailureMemory: "创建候选"',
    "receipt_failure_memory_preview_label_en": 'previewFailureMemory: "Preview memory"',
    "receipt_failure_memory_preview_label_zh": 'previewFailureMemory: "预览记忆"',
    "receipt_failure_memory_result": "receiptFailureMemoryResult",
    "receipt_failure_memory_action_flag": 'isReceiptFailureMemoryRecovery: item.source === "receipt_failure_memory"',
    "receipt_failure_memory_sort": "candidate.isReceiptFailureMemoryRecovery ? 114",
    "receipt_failure_memory_summary_render": "failure memory ${operatorPlanSummary.receipt_failure_memory_candidates}",
    "evidence_remediation_queue_flag": "isEvidenceRemediation",
    "evidence_remediation_queue_marker": "handoff_remediation_chain",
    "evidence_remediation_queue_sort": "candidate.isEvidenceRemediation ? 112",
    "evidence_remediation_queue_label": "evidence remediation",
    "operator_handoff_data": "operatorHandoff",
    "operator_handoff_label_en": 'operatorHandoffTitle: "Operator handoff"',
    "operator_handoff_label_zh": 'operatorHandoffTitle: "Operator 交接包"',
    "operator_handoff_summary_en": 'operatorHandoffSummary: "Read-only handoff package',
    "operator_handoff_summary_zh": 'operatorHandoffSummary: "给 Hermes、OpenClaw、Codex',
    "operator_handoff_commands": "operatorHandoff?.work_order?.commands",
    "operator_handoff_loop_self_check_loader": "loadOperatorLoopSelfCheck",
    "operator_handoff_loop_self_check_payload": "operatorLoopSelfCheck",
    "operator_handoff_loop_self_check_command": "loopSelfCheckCommand",
    "operator_handoff_loop_self_check_label_en": 'loopSelfCheckTitle: "Pre-advance check"',
    "operator_handoff_loop_self_check_label_zh": 'loopSelfCheckTitle: "推进前自检"',
    "operator_handoff_loop_self_check_copy": "copyIntakeCommand(loopSelfCheckCommand)",
    "operator_handoff_loop_self_check_gates_label": "loopSelfCheckGates",
    "operator_handoff_loop_self_check_gate_summaries": "loopSelfCheckGateSummaries",
    "operator_handoff_loop_self_check_policy_gate": "policy_contract",
    "operator_handoff_loop_self_check_receipt_eval_gate": "receipt_evaluations",
    "operator_handoff_loop_self_check_audit_gate": "audit_ledger",
    "operator_handoff_loop_self_check_write_guard_gate": "localWriteGuardSelfCheckGate",
    "operator_handoff_loop_self_check_write_guard_id": "local_ui_write_guard",
    "operator_handoff_loop_self_check_write_guard_label": "label: copy.localWriteGuard",
    "operator_handoff_loop_self_check_write_guard_status": 'loopSelfCheckGateStatus("local_ui_write_guard")',
    "operator_handoff_loop_self_check_write_guard_detail": "localWriteGuardSelfCheckGate.gate_status",
    "operator_handoff_advance_loop_source": "operatorHandoff?.work_order?.advance_loop",
    "operator_handoff_advance_loop_label_en": 'advanceLoopTitle: "Bounded advance"',
    "operator_handoff_advance_loop_label_zh": 'advanceLoopTitle: "受限推进"',
    "operator_handoff_advance_loop_preview": "advanceLoopPreviewCommand",
    "operator_handoff_advance_loop_confirm": "advanceLoopConfirmCommand",
    "operator_handoff_advance_loop_copy_preview": "copyIntakeCommand(advanceLoopPreviewCommand)",
    "operator_handoff_advance_loop_copy_confirm": "copyIntakeCommand(advanceLoopConfirmCommand)",
    "operator_handoff_advance_loop_policy": "advanceLoopPolicy",
    "operator_handoff_advance_loop_policy_label_en": 'advanceLoopPolicyLabel: "Policy"',
    "operator_handoff_advance_loop_policy_label_zh": 'advanceLoopPolicyLabel: "策略"',
    "operator_handoff_advance_loop_policy_id": "advanceLoopPolicyId",
    "operator_handoff_advance_loop_policy_version": "advanceLoopPolicyVersion",
    "operator_handoff_control_summary": "handoffControlSummary",
    "operator_handoff_control_json": "control_summary: operatorHandoff.control_summary",
    "operator_handoff_control_step": "handoffControlStep",
    "operator_handoff_control_command": "handoffControlCommand",
    "operator_handoff_control_copy_only": "handoffControlSummary.server_executes_shell",
    "operator_health_control_summary_compact": "operatorHealthControlSummary",
    "operator_health_loop_control_gate_compact": "operatorHealthLoopControl",
    "operator_health_loop_control_status": "loopControlGateStatus",
    "operator_health_loop_control_readback": "loopControlReadbackSource",
    "operator_health_loop_control_cache_refresh": "loopControlRefreshRequired",
    "operator_health_loop_control_top_badge": "copy.loopControlTitle}: ${loopControlGateStatus}",
    "operator_health_loop_control_metric": "{ label: copy.loopControlTitle, value: loopControlSelectedGate, status: loopControlGateStatus }",
    "operator_handoff_control_readback_label_en": 'controlReadbackSource: "Readback source"',
    "operator_handoff_control_readback_label_zh": 'controlReadbackSource: "回读来源"',
    "operator_handoff_control_cache_label_en": 'cacheRefresh: "Cache refresh"',
    "operator_handoff_control_cache_label_zh": 'cacheRefresh: "缓存刷新"',
    "operator_handoff_control_source_label": "commandSource",
    "operator_handoff_control_readback_source": "agentops operator advance-loop --confirm-advance",
    "operator_handoff_sources": "operatorHandoffSources",
    "operator_handoff_evidence_report_summary": "operatorHandoffSummary?.evidence_report_ready",
    "operator_handoff_evidence_report_status": "operatorHandoffSummary?.evidence_report_status",
    "operator_handoff_sources_three": "Object.entries(operatorHandoffSources).slice(0, 3)",
    "operator_handoff_evidence_report_label": "copy.evidenceReportTitle",
    "operator_handoff_evidence_receipt_state": "handoffEvidenceReceiptState",
    "operator_handoff_evidence_receipt_verified": "handoffEvidenceReceiptState?.verified",
    "operator_handoff_evidence_receipt_hash": "handoffEvidenceReceiptState.receipt_hash",
    "operator_handoff_evidence_remediation_summary": "handoffEvidenceRemediationSummary",
    "operator_handoff_evidence_remediation_items": "handoffEvidenceRemediationSummary.items",
    "operator_handoff_evidence_remediation_workflow_ready": "handoffEvidenceRemediationSummary.workflow_ready_steps",
    "operator_handoff_evidence_remediation_workflow_blocked": "handoffEvidenceRemediationSummary.workflow_blocked_steps",
    "operator_handoff_evidence_remediation_stage_rows": "remediationWorkflowRows",
    "operator_handoff_evidence_remediation_next_workflow_step": "next_workflow_step",
    "operator_handoff_evidence_remediation_next_safe_kind": "next_safe_command_kind",
    "operator_handoff_evidence_remediation_receipt_next": "receipt_next_command",
    "operator_handoff_evidence_remediation_blocked_reason": "blocked_reason",
    "operator_handoff_evidence_remediation_workflow_label": "remediationWorkflow",
    "operator_action_queue_remediation_workflow_step_id": "remediationWorkflowStepId",
    "operator_action_queue_remediation_workflow_kind": "remediationWorkflowKind",
    "operator_action_queue_remediation_workflow_prerequisite": "remediationWorkflowPrerequisite",
    "operator_action_queue_remediation_workflow_mutating": "remediationWorkflowMutating",
    "operator_action_queue_remediation_workflow_confirm": "remediationWorkflowConfirmRequired",
    "operator_handoff_receipt_state": "operatorHandoff.receipt_state.coverage",
    "operator_handoff_review_state": "operatorHandoff.review_state.loop_record",
    "operator_handoff_loop_health_json": "loop_health: operatorHandoff.loop_health",
    "operator_handoff_loop_health_label_en": 'loopHealth: "Loop health"',
    "operator_handoff_loop_health_label_zh": 'loopHealth: "Loop 健康"',
    "operator_handoff_loop_risks_label_en": 'loopRisks: "Risks"',
    "operator_handoff_loop_risks_label_zh": 'loopRisks: "风险"',
    "operator_handoff_loop_health_score": "operatorHandoff.loop_health?.score",
    "operator_handoff_loop_health_next_action": "operatorHandoff.loop_health?.next_action",
    "operator_handoff_auth_boundary_en": 'authBoundary: "Auth boundary"',
    "operator_handoff_auth_boundary_zh": 'authBoundary: "认证边界"',
    "operator_handoff_auth_json": "auth: operatorHandoff.auth",
    "operator_handoff_auth_render": "operatorHandoff.auth?.required_scope",
    "operator_handoff_loop_health_json": "loop_health: operatorHandoff.loop_health",
    "operator_handoff_loop_health_en": 'loopHealth: "Loop health"',
    "operator_handoff_loop_health_zh": 'loopHealth: "Loop 健康"',
    "operator_handoff_loop_risks": "operatorHandoff.loop_health?.risks?.length",
    "operator_handoff_json_copy": "copyIntakeCommand(operatorHandoffJson)",
    "operator_handoff_command_copy": "copyIntakeCommand(handoffCommand)",
    "close_gap_verify": 'isCloseEvidenceGapCommand(item.command) ? "agentops operator action-plan --limit 20"',
    "fleet_verify": 'verifyAction: "agentops worker status"',
    "integration_inbox_verify": 'verifyAction: "agentops commander inbox --limit 5"',
    "synthesis_verify": 'verifyAction: "agentops commander board --limit 20"',
    "local_readiness_verify": 'verifyAction: "agentops local readiness"',
    "verify_label_en": 'verifyAfterAction: "Verify"',
    "verify_label_zh": 'verifyAfterAction: "验收"',
    "verify_render": "{copy.verifyAfterAction}: {item.verifyAction}",
    "verify_copy_button": "copyIntakeCommand(item.verifyAction)",
    "receipt_loader": "loadOperatorActionReceipts(8)",
    "receipt_writer": "recordOperatorActionReceipt({",
    "record_action_label_en": 'recordActionReceipt: "Record"',
    "record_action_label_zh": 'recordActionReceipt: "记账"',
    "verify_receipt_label_en": 'recordVerifyReceipt: "Verify receipt"',
    "verify_receipt_label_zh": 'recordVerifyReceipt: "验收记账"',
    "copy_receipt_cli_label_en": 'copyReceiptCommand: "Copy receipt CLI"',
    "copy_receipt_cli_label_zh": 'copyReceiptCommand: "复制记账 CLI"',
    "copy_verify_receipt_cli_label_en": 'copyVerifyReceiptCommand: "Copy verify CLI"',
    "copy_verify_receipt_cli_label_zh": 'copyVerifyReceiptCommand: "复制验收 CLI"',
    "receipt_summary": "operatorActionReceipts.summary.receipts",
    "receipt_proof_label_en": 'receiptProof: "Receipt"',
    "receipt_proof_label_zh": 'receiptProof: "收据证明"',
    "receipt_needed_label_en": 'receiptNeeded: "Needs receipt"',
    "receipt_needed_label_zh": 'receiptNeeded: "需验收收据"',
    "receipt_matcher": "latestReceiptForAction",
    "receipt_no_verify_only_match": "wantedAction === String(receipt.action_command",
    "receipt_signature_match": "wantedSignature === String(receipt.action_signature",
    "receipt_short_hash": "receiptShortHash",
    "backend_receipt_status": "receiptStatus: item.receipt_status",
    "backend_action_signature": "actionSignature: item.action_signature",
    "receipt_signature_writer": "action_signature:",
    "backend_receipt_verified": "receiptVerified: item.receipt_verified",
    "backend_receipt_required": "receiptRequired: item.receipt_required",
    "backend_verify_command": "verifyAction: item.verify_command",
    "backend_receipt_record_command": "receiptRecordCommand: item.receipt_record_command",
    "backend_receipt_record_confirm_command": "receiptRecordConfirmCommand: item.receipt_record_confirm_command",
    "backend_receipt_verify_record_command": "receiptVerifyRecordCommand: item.receipt_verify_record_command",
    "copy_receipt_record_command": "copyIntakeCommand(receiptRecordCommand)",
    "copy_receipt_verify_record_command": "copyIntakeCommand(receiptVerifyRecordCommand)",
    "render_copy_receipt_cli": "copy.copyReceiptCommand",
    "render_copy_verify_receipt_cli": "copy.copyVerifyReceiptCommand",
    "receipt_coverage_recovery_flag": 'isReceiptCoverageRecovery: item.source === "receipt_coverage"',
    "receipt_coverage_recovery_sort": "candidate.isReceiptCoverageRecovery ? 115",
    "receipt_coverage_source": "operatorReceiptCoverage",
    "receipt_coverage_display": "receipt coverage",
    "receipt_coverage_verified_required": "operatorReceiptCoverage.verified}/${operatorReceiptCoverage.required",
    "receipt_coverage_stale_missing": "operatorReceiptCoverage.stale} · missing ${operatorReceiptCoverage.missing",
    "verified_receipt_sort": "!candidateReceiptVerified(candidate) ? 80",
    "receipt_sensitive_queue_key": "actionReceiptKey",
    "queue_receipt_display": "{copy.receiptProof}: {queueReceiptStatus}",
    "queue_receipt_needed_display": "{copy.receiptNeeded}: {verifyAction || item.action}",
    "loop_receipt_display": "{copy.receiptProof}: {stepReceipt.status}",
    "recorded_receipt_status": 'recordActionQueueReceipt(item, "recorded")',
    "verified_receipt_status": 'recordActionQueueReceipt(item, "verified")',
}

EXPECTED_LIVE_API_MARKERS = {
    "operator_health_summary_control_status": "control_status?: string;",
    "operator_health_summary_control_mode": "control_mode?: string;",
    "operator_health_control_summary_type": 'control_summary?: OperatorHandoffPayload["control_summary"];',
    "operator_health_loop_control_type": "loop_control?: {",
    "operator_health_control_summary_fallback": 'operation: "operator_loop_control_summary"',
    "operator_health_loop_control_fallback": 'control_readback_source: "agentops operator advance-loop --confirm-advance"',
    "operator_health_control_raw": "const controlRaw = typeof raw.control_summary",
    "operator_health_loop_control_raw": "const loopControlRaw = typeof raw.loop_control",
    "operator_health_control_status_normalize": "control_status: summaryRaw.control_status",
    "operator_health_loop_control_next_action_normalize": "next_action: loopControlRaw.next_action",
    "operator_health_loop_control_refresh_normalize": "refresh_cache_required_after_receipt: loopControlRaw.refresh_cache_required_after_receipt",
    "operator_health_loop_control_token_omitted": "token_omitted: loopControlRaw.token_omitted",
}

FORBIDDEN_MARKERS = {
    "initial_daemon_log_prefetch": "Promise.all(WORKER_ADAPTERS.map(adapter => loadWorkerDaemonLogs(adapter)))",
    "data_daemon_logs_readback": "data?.daemonLogs",
    "page_level_use_live_data": "useLiveData(",
    "monolithic_initial_loader": "const [metrics, demoReadiness, workerStatus",
    "monolithic_scoped_loader": "const [operatorLoopAudit, operatorHandoff, operatorHealth, operatorLoopSelfCheck]",
}


def main() -> int:
    source = AI_EMPLOYEES.read_text(encoding="utf-8")
    live_api_source = LIVE_API.read_text(encoding="utf-8")
    failures: list[str] = []

    for label, marker in EXPECTED_MARKERS.items():
        if marker not in source:
            failures.append(f"missing {label}: {marker}")
    for label, marker in EXPECTED_LIVE_API_MARKERS.items():
        if marker not in live_api_source:
            failures.append(f"missing live api {label}: {marker}")
    for label, marker in FORBIDDEN_MARKERS.items():
        if marker in source:
            failures.append(f"forbidden {label}: {marker}")

    queue_index = source.find("const actionQueueCandidates")
    verify_render_index = source.find("{copy.verifyAfterAction}: {item.verifyAction}")
    if queue_index < 0:
        failures.append("operator action queue candidate block missing")
    if verify_render_index < 0:
        failures.append("operator action queue verify render block missing")
    if queue_index >= 0 and verify_render_index >= 0 and verify_render_index < queue_index:
        failures.append("verify render appears before queue candidate construction")

    live_api_secret_scan_source = live_api_source.replace("customer-task-templates", "customer_task_templates")
    secret_hits = [pattern.pattern for pattern in SECRET_PATTERNS if pattern.search(source) or pattern.search(live_api_secret_scan_source)]
    if secret_hits:
        failures.append(f"secret-like pattern found in UI source: {secret_hits}")

    result = {
        "ok": not failures,
        "operation": "operator_action_queue_ui_contract",
        "files": [
            str(AI_EMPLOYEES.relative_to(ROOT)),
            str(LIVE_API.relative_to(ROOT)),
        ],
        "markers_checked": len(EXPECTED_MARKERS) + len(EXPECTED_LIVE_API_MARKERS) + len(FORBIDDEN_MARKERS),
        "failures": failures,
        "safety": {
            "read_only": True,
            "ledger_mutated": False,
            "live_execution_performed": False,
            "token_omitted": True,
        },
    }
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
