#!/usr/bin/env python3
"""Product acceptance wrapper for the remote-worker operator path.

The wrapper is intentionally non-live by default: it runs read-only operator
checks plus mock-only remote worker smokes. It captures child output for
validation, but only emits a compact redacted JSON summary.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
CLI = ROOT / "scripts" / "agentops"
DEFAULT_BASE_URL = "http://127.0.0.1:8787"


TOKEN_PATTERNS = [
    re.compile(r"Authorization:\s*[^\s,;]+", re.IGNORECASE),
    re.compile(r"Bearer\s+[A-Za-z0-9._~+/\-=]{12,}", re.IGNORECASE),
    re.compile(r"\bAGENTOPS_API_KEY\s*=\s*(?!<paste\b)[^\s]+", re.IGNORECASE),
    re.compile(r"\bAGENTOPS_API_KEY=(?!<paste\b)[^\s]+", re.IGNORECASE),
    re.compile(r"\bsk-[A-Za-z0-9_-]{20,}"),
    re.compile(r"\bntn_[A-Za-z0-9_-]{20,}"),
]
AGENT_TOKEN_RE = re.compile(r"\b(?:agtok|agtsess)_[A-Za-z0-9_-]{24,}\b")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Run non-live/read-only and mock remote-worker product acceptance checks."
    )
    parser.add_argument("--base-url", default=DEFAULT_BASE_URL)
    parser.add_argument(
        "--skip-launch-packet-smoke",
        action="store_true",
        help="Skip the optional mock launch-packet/session smoke.",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=300,
        help="Per-command timeout in seconds.",
    )
    return parser


def http_get_json(base_url: str, path: str, timeout: int = 10) -> tuple[int, dict[str, Any]]:
    req = urllib.request.Request(
        base_url.rstrip("/") + path,
        headers={"Accept": "application/json"},
        method="GET",
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            raw = resp.read().decode("utf-8")
            return resp.status, json.loads(raw) if raw else {}
    except urllib.error.HTTPError as exc:
        raw = exc.read().decode("utf-8", errors="replace")
        try:
            body = json.loads(raw)
        except Exception:
            body = {"error": exc.reason, "raw": raw[:400]}
        return exc.code, body


def probably_secret_agent_token(value: str) -> bool:
    """Differentiate raw agtok/agtsess secrets from stable safe refs.

    Stable token/session ids generated by MIS are lowercase slug/hash refs.
    Raw secrets are urlsafe random strings and normally contain mixed case or
    hyphens. This keeps safe ids from failing the acceptance wrapper while still
    catching raw one-time tokens and session tokens in stdout/stderr.
    """
    suffix = value.split("_", 1)[1]
    return len(suffix) >= 28 and bool(re.search(r"[A-Z-]", suffix))


def token_leaked(text: str) -> bool:
    if any(pattern.search(text) for pattern in TOKEN_PATTERNS):
        return True
    return any(probably_secret_agent_token(match.group(0)) for match in AGENT_TOKEN_RE.finditer(text))


def redact(text: str) -> str:
    redacted = text
    for pattern in TOKEN_PATTERNS:
        redacted = pattern.sub("<redacted-token>", redacted)
    redacted = AGENT_TOKEN_RE.sub(
        lambda match: "<redacted-agent-token>" if probably_secret_agent_token(match.group(0)) else match.group(0),
        redacted,
    )
    return redacted


def parse_json(text: str) -> dict[str, Any]:
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return {}


def run_command(
    name: str,
    cmd: list[str],
    *,
    env: dict[str, str],
    timeout: int,
) -> dict[str, Any]:
    proc = subprocess.run(
        cmd,
        cwd=ROOT,
        env=env,
        capture_output=True,
        text=True,
        timeout=timeout,
        check=False,
    )
    combined = proc.stdout + "\n" + proc.stderr
    payload = parse_json(proc.stdout) or parse_json(proc.stderr)
    command: dict[str, Any] = {
        "name": name,
        "returncode": proc.returncode,
        "ok": proc.returncode == 0 and not token_leaked(combined),
        "token_leaked": token_leaked(combined),
    }
    if payload:
        command["payload"] = payload
    if proc.returncode != 0:
        command["error"] = redact((proc.stderr or proc.stdout)[-600:])
    return command


def safe_env(config_path: Path, base_url: str) -> dict[str, str]:
    env = os.environ.copy()
    env["AGENTOPS_CONFIG"] = str(config_path)
    env["AGENTOPS_BASE_URL"] = base_url
    env["AGENTOPS_WORKSPACE_ID"] = "local-demo"
    env.pop("AGENTOPS_API_KEY", None)
    env.pop("AGENTOPS_AGENT_ID", None)
    return env


def command_summary(item: dict[str, Any]) -> dict[str, Any]:
    payload = item.get("payload") if isinstance(item.get("payload"), dict) else {}
    summary: dict[str, Any] = {
        "name": item.get("name"),
        "ok": item.get("ok") is True,
        "returncode": item.get("returncode"),
    }
    if item.get("error"):
        summary["error"] = item["error"]

    name = item.get("name")
    if name == "agentops doctor":
        summary["doctor_ok"] = payload.get("ok")
        summary["auth_source"] = (payload.get("auth") or {}).get("api_key_source")
        summary["gateway_status"] = ((payload.get("gateway") or {}).get("status"))
    elif name == "agentops worker status":
        summary["status"] = payload.get("status")
        summary["remote_worker_count"] = payload.get("remote_worker_count")
        summary["fleet_health"] = (payload.get("fleet_health") or {}).get("overall")
    elif name == "agentops worker readiness":
        summary["status"] = payload.get("status")
        summary["recommended_adapter"] = (payload.get("summary") or {}).get("recommended_adapter")
        summary["live_execution_performed"] = payload.get("live_execution_performed")
    elif name == "agentops worker preflight --adapter mock":
        summary["preflight_ok"] = payload.get("ok")
        summary["live_execution_performed"] = payload.get("live_execution_performed")
    elif name == "remote_agent_token_worker_smoke.py --adapter mock":
        summary["run_id"] = payload.get("run_id")
        summary["adapter"] = payload.get("adapter")
        summary["worker_processed"] = payload.get("worker_processed")
        summary["revoked"] = (payload.get("revocation") or {}).get("revoked")
    elif name == "remote_launch_packet_worker_smoke.py":
        smoke = payload.get("smoke") or {}
        summary["run_id"] = smoke.get("run_id")
        summary["adapter"] = smoke.get("adapter")
        summary["session_path"] = bool(smoke.get("session_id"))
        summary["token_omitted"] = smoke.get("token_omitted")
    return summary


def validate_remote_path(commands: list[dict[str, Any]]) -> tuple[dict[str, Any], list[str]]:
    failures: list[str] = []
    by_name = {item.get("name"): item for item in commands}

    doctor = by_name.get("agentops doctor", {})
    doctor_payload = doctor.get("payload") or {}
    if doctor.get("returncode") != 0 or doctor_payload.get("auth", {}).get("token_omitted") is not True:
        failures.append("agentops doctor did not prove token omission")

    status = by_name.get("agentops worker status", {})
    status_payload = status.get("payload") or {}
    if status.get("returncode") != 0 or status_payload.get("remote_worker_health", {}).get("token_omitted") is not True:
        failures.append("agentops worker status did not prove remote token omission")

    readiness = by_name.get("agentops worker readiness", {})
    readiness_payload = readiness.get("payload") or {}
    if readiness.get("returncode") != 0 or readiness_payload.get("live_execution_performed") is not False:
        failures.append("agentops worker readiness did not prove non-live route selection")
    if (readiness_payload.get("summary") or {}).get("recommended_adapter") not in {"mock", "hermes", "openclaw"}:
        failures.append("agentops worker readiness did not include a recommended adapter")

    preflight = by_name.get("agentops worker preflight --adapter mock", {})
    preflight_payload = preflight.get("payload") or {}
    if preflight.get("returncode") != 0 or preflight_payload.get("live_execution_performed") is not False:
        failures.append("mock worker preflight did not stay non-live")

    token_smoke = by_name.get("remote_agent_token_worker_smoke.py --adapter mock", {})
    token_payload = token_smoke.get("payload") or {}
    token_run_id = token_payload.get("run_id")
    if token_smoke.get("returncode") != 0 or token_payload.get("ok") is not True or not token_run_id:
        failures.append("remote token worker mock smoke did not create completed run evidence")
    if token_payload.get("adapter") != "mock":
        failures.append("remote token worker smoke did not use mock adapter")

    launch_smoke = by_name.get("remote_launch_packet_worker_smoke.py", {})
    launch_payload = launch_smoke.get("payload") or {}
    launch_data = launch_payload.get("smoke") or {}
    launch_present = bool(launch_smoke)
    session_path = bool(launch_data.get("session_id"))
    if launch_present and (launch_smoke.get("returncode") != 0 or launch_payload.get("ok") is not True or not session_path):
        failures.append("remote launch packet/session smoke did not prove session path")

    return {
        "doctor": doctor.get("returncode") == 0,
        "worker_status": status.get("returncode") == 0,
        "worker_readiness": readiness.get("returncode") == 0,
        "mock_preflight": preflight.get("returncode") == 0,
        "enrollment_token_path": token_payload.get("ok") is True,
        "session_path": session_path if launch_present else None,
        "mock_adapter_only": token_payload.get("adapter") == "mock"
        and (not launch_present or launch_data.get("adapter") == "mock"),
        "operator_perspective": "agentops doctor -> worker status -> worker readiness -> mock remote worker execution",
    }, failures


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    base_url = args.base_url.rstrip("/")

    status_code, health = http_get_json(base_url, "/api/agent-gateway/status")
    if status_code != 200:
        print(json.dumps(
            {
                "ok": False,
                "base_url": base_url,
                "commands": [],
                "remote_worker_path": {},
                "token_leaked": False,
                "live_execution_performed": False,
                "limitation": f"local server unavailable or not ready at {base_url}",
                "status_code": status_code,
                "status": health.get("status") or health.get("error"),
            },
            ensure_ascii=False,
            sort_keys=True,
        ))
        return 1

    with tempfile.TemporaryDirectory(prefix="agentops-remote-product-") as tmp:
        env = safe_env(Path(tmp) / "config.json", base_url)
        commands: list[dict[str, Any]] = []
        command_specs = [
            ("agentops doctor", [str(CLI), "--base-url", base_url, "doctor"]),
            ("agentops worker status", [str(CLI), "--base-url", base_url, "worker", "status"]),
            ("agentops worker readiness", [str(CLI), "--base-url", base_url, "worker", "readiness"]),
            (
                "agentops worker preflight --adapter mock",
                [str(CLI), "--base-url", base_url, "worker", "preflight", "--adapter", "mock"],
            ),
        ]
        smoke_path = ROOT / "scripts" / "remote_agent_token_worker_smoke.py"
        if smoke_path.exists():
            command_specs.append((
                "remote_agent_token_worker_smoke.py --adapter mock",
                [sys.executable, str(smoke_path), "--base-url", base_url, "--adapter", "mock"],
            ))
        else:
            commands.append({
                "name": "remote_agent_token_worker_smoke.py --adapter mock",
                "returncode": 127,
                "ok": False,
                "token_leaked": False,
                "error": "scripts/remote_agent_token_worker_smoke.py not found",
            })

        launch_path = ROOT / "scripts" / "remote_launch_packet_worker_smoke.py"
        if not args.skip_launch_packet_smoke and launch_path.exists():
            command_specs.append((
                "remote_launch_packet_worker_smoke.py",
                [sys.executable, str(launch_path), "--base-url", base_url],
            ))

        for name, cmd in command_specs:
            commands.append(run_command(name, cmd, env=env, timeout=args.timeout))

    leaked = any(item.get("token_leaked") for item in commands)
    remote_worker_path, failures = validate_remote_path(commands)
    live_execution_performed = any(
        (item.get("payload") or {}).get("live_execution_performed") is True
        for item in commands
        if isinstance(item.get("payload"), dict)
    )
    token_smoke = next(
        (item for item in commands if item.get("name") == "remote_agent_token_worker_smoke.py --adapter mock"),
        {},
    )
    launch_smoke = next((item for item in commands if item.get("name") == "remote_launch_packet_worker_smoke.py"), {})
    token_payload = token_smoke.get("payload") or {}
    launch_payload = (launch_smoke.get("payload") or {}).get("smoke") or {}
    created_run_id = token_payload.get("run_id") or launch_payload.get("run_id")
    ok = bool(
        not leaked
        and not live_execution_performed
        and all(item.get("ok") is True for item in commands)
        and not failures
    )
    result: dict[str, Any] = {
        "ok": ok,
        "base_url": base_url,
        "commands": [command_summary(item) for item in commands],
        "remote_worker_path": remote_worker_path,
        "token_leaked": leaked,
        "live_execution_performed": False,
    }
    if created_run_id:
        result["created_run_id"] = created_run_id
    if failures:
        result["failures"] = failures
    print(json.dumps(result, ensure_ascii=False, sort_keys=True))
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
