import type { LocaleMode } from "../../context/PreferencesContext";

const COPY = {
  en: {
    eyebrow: "Operate",
    title: "Mission Control",
    description: "Start with work that needs a human decision, then inspect active packages, workforce health and evidence-backed incidents.",
    live: "Live read models",
    loading: "Loading",
    refresh: "Refresh",
    partial: "Some read models are unavailable. Available panels remain live; missing values are not fabricated.",
    attention: { title: "Attention Queue", description: "Prioritized operator actions and review items from the MIS ledger.", open: "Open", emptyTitle: "No operator action requires attention", emptyDescription: "The queue is empty for the current workspace and available read models." },
    packages: { title: "Active Work Packages", description: "Commander packages with status, owner, risk and evidence coverage.", open: "Open", emptyTitle: "No active work packages", emptyDescription: "Create or dispatch Commander work packages from the workforce workspace." },
    workforce: { title: "Workforce Health", description: "Local daemons, remote workers and stuck work from the worker-fleet read model.", open: "Open", emptyTitle: "Worker status unavailable" },
    activity: { title: "Incidents & Recent Activity", description: "Failed or blocked work first, followed by recent runs.", open: "Open", emptyTitle: "No recent incidents", emptyDescription: "No failed or blocked tasks or runs were returned in the current window." },
    pixel: { title: "Pixel Office Preview", description: "A read-only spatial view of the same MIS state. Open a room to reach its canonical ledger.", open: "Open", emptyTitle: "Pixel Office unavailable" },
    unavailablePackages: "Work-package read model unavailable",
    unavailablePackagesDescription: "The UI intentionally shows no number instead of substituting task counts.",
    activePackages: "Active work packages",
    runningAgents: "Running agents",
    pendingReviews: "Pending reviews",
    incidents24: "24h incidents",
    packagesVisible: "packages visible",
    agentsTotal: "agents total",
    approvals: "security approvals",
    failedTasks: "blocked or failed tasks",
    evidence: "evidence",
    daemons: "Local daemons",
    stuck: "Stuck work",
    lanes: "Fleet lanes",
    unavailableMission: "Mission Control could not load",
  },
  zh: {
    eyebrow: "运营",
    title: "任务控制台",
    description: "先处理需要人类判断的事项，再查看活跃工作包、员工健康和有证据支持的故障。",
    live: "实时只读模型",
    loading: "加载中",
    refresh: "刷新",
    partial: "部分只读模型不可用。其余面板仍使用实时数据，缺失值不会用假数据补齐。",
    attention: { title: "待处理队列", description: "来自 MIS 权威账本的优先级操作建议与复核事项。", open: "打开", emptyTitle: "当前没有需要处理的操作项", emptyDescription: "当前工作区与可用只读模型的待处理队列为空。" },
    packages: { title: "活跃工作包", description: "显示 Commander 工作包的状态、负责人、风险与证据覆盖。", open: "打开", emptyTitle: "当前没有活跃工作包", emptyDescription: "可在员工工作区创建或分发 Commander 工作包。" },
    workforce: { title: "员工与 Worker 健康", description: "本地 daemon、远程 Worker 与卡住工作的只读状态。", open: "打开", emptyTitle: "Worker 状态不可用" },
    activity: { title: "故障与最近活动", description: "先展示失败或阻塞项，再展示最近运行。", open: "打开", emptyTitle: "近期没有故障", emptyDescription: "当前窗口没有返回失败或阻塞任务或运行。" },
    pixel: { title: "像素办公室预览", description: "同一 MIS 状态的只读空间视图；房间会跳转到权威账本。", open: "打开", emptyTitle: "像素办公室不可用" },
    unavailablePackages: "工作包只读模型不可用",
    unavailablePackagesDescription: "界面不会拿任务数量冒充工作包数量。",
    activePackages: "活跃工作包",
    runningAgents: "运行中 Agent",
    pendingReviews: "待复核",
    incidents24: "24 小时故障",
    packagesVisible: "个工作包可见",
    agentsTotal: "个 Agent",
    approvals: "个安全审批",
    failedTasks: "个阻塞或失败任务",
    evidence: "条证据",
    daemons: "本地 daemon",
    stuck: "卡住工作",
    lanes: "集群通道",
    unavailableMission: "无法加载任务控制台",
  },
};

export function missionControlCopy(locale: LocaleMode) {
  return locale === "zh" ? COPY.zh : COPY.en;
}
